require("config.globals")
require("config.options")
require("config.keymaps")
require("config.autocmds")

require("plugins.lsp")
require("plugins.treesitter")
require("plugins.colourscheme")
require("plugins.completion")
require("plugins.telescope")
require("plugins.oil")
require("plugins.conform")
require("plugins.flash")
require("plugins.gitsigns")
require("plugins.todo_comments")
require("plugins.undotree")
require("plugins.accelerate")

require("plugins.graft")
